# Generated by Django 4.0.1 on 2022-08-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
