# Generated by Django 4.0.1 on 2022-08-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_replies_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
