# Generated by Django 4.0.1 on 2022-08-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_message_replies_delete_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replies',
        ),
    ]
